name: Deploy Frontend Application

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.20.2' 

    - name: Install Dependencies
      run: yarn install

    - name: Build Project
      run: yarn build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Adjust this to your AWS region

    - name: Upload to S3
      run: aws s3 sync ./build s3://robin-gitaction --delete

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"

