name: Deploy Frontend Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.0'
        cache: 'yarn' 

    - name: Install Dependencies
      run: yarn install

    - name: Increase Version
      run: |
        git config --global user.email "robinsonpujara@gmail.com"
        git config --global user.name "Robinson"
        yarn version --minor --no-git-tag-version
      env:
        CI: true

    - name: Build Project
      run: yarn build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Adjust this to your AWS region

    - name: Upload to S3
      run: aws s3 sync ./dist s3://robin-gitaction --delete

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id EMOFLLTKSQQ70 --paths "/*"

    # Commit and push the updated package.json with new version
    - name: Commit version bump
      run: |
        git commit -am "Bump version"
        git push
